name: flutter_getx_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2            
  flutter_screenutil: ^5.9.3 
  intl: any
  cupertino_icons: ^1.0.8
  get_storage: 2.1.1
  flutter_svg: 2.1.0
  google_fonts: 6.2.1
  loading_animation_widget: 1.3.0
  intl_phone_field: 3.2.0
  pinput: 5.0.1
  carousel_slider: 5.0.0
  dots_indicator: 4.0.1
  flutter_rating: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
